### PR TITLE
Few build fixes & small label improvement

### PR DESCRIPTION
**Pull request by mvdfugro**
Hi Jamie & Doug,

A few changes that I had to make to get PAMGuard to compile plus the actual change I actually wanted to push :-)

- I flipped 'pamguard.org' to 'org.pamguard' in the x3 repo folder - that seems to fix the issue with Maven not picking it up. The package itself seems to use 'org.pamguard.*' so using that as package prefix made sense to me.
- I can't reach the talanlabs repo and it doesn't seem to be required to build
- I'm not entirely sure about the generics fix - IntelliJ was very much unhappy about the existing code but Maven didn't seem to care when building, so I'm not entirely sure if this is just a setting for the Java compiler where it can be stricter or less strict. Either way, this got everything to compile. **I have not tested whether all serialization is still functional** - I hope you have a better view on the risks with touching this code. Another alternative could be to create a non-generic base class (`DataAnnotation<T> extends DataAnnotation`) but I'm not sure if that works in Java.

The actual change is clarifying the axis and units for the FFT display.

I've also been playing with automating the build in GitHub (see https://github.com/mvdfugro/PAMGuard/tree/refs/heads/github-workflow) but that results in a .jar without GUI components so that needs a little bit more work.

Cheers,
Merlijn

### CODE REVIEW

**Comment by macster110** [comment]
Hi Merlijn. Thanks for this! We will do a code review and get back to you about this. Definitely agree that we need to be more studious about our units!

**Comment by macster110** [comment]
All looks good apart form apart from the unit Strings. You are right to pick up that these need changed, however, all units are now supposed to be handled through the GloablMediumManager. The global medium manager ensures that we can change sound medium i.e. from water to air and change units automtically. So for example, in water dB are referenced to 1uPa and in air it's 20uPa. You therefore need to replace all hard coded units with something like. 

```Java
String label = String.format("dB (%s)", PamController.getInstance().getGlobalMediumManager().getdBSensString());
```

We also do not have a dB re 1uPa^2/Hz function for this so we need to add a function ```getdBHzRefString()``` to  PamController.soundMedium.GlobalMediumManager to sort this out. 

Finally please do not use the micro symbol in code and instead use \u00B5. We have had issues with micro symbol when building for different platforms.

**Comment by mvdfugro** [comment]
I had to fiddle around a bit to make the `PamController` available in a test without UI items popping up. Tests were mostly for my own development process, please feel free to not merge that commit if you'd rather not have the `PamControllerTestHelper` :-)

Units-wise: 400µPa²s seems to be what people actually use for SEL (per https://en.wikipedia.org/wiki/Sound_exposure#Sound_exposure_level), I couldn't find a reference for PSD in air. However changing the units would require significant changes to the display logic so this seemed like a sensible enough approach.

**Comment by macster110** [comment]
Hi Merlijn. This looks good. So far we have kept unit tests in src/tests with the idea that we may eventually convert PAMGuard to a more standard folder layout for Maven. It also helps to run tests if they are within a certain package.  

Would be happy to hear other thoughts though on whether tests should be within a package per module...that makes considering the structure of PAMGuard and we could easily change at this stage...

**Comment by macster110** [comment]
Great, I think this all looks good -merged. I'll check out the classifier tests to see what's going on - thanks for the heads up. 
And thanks for all your efforts with this!

**Pull request merged**
